# Define a list of samples
samples:
    - SRR29848602/H2I
    - SRR29848599/A2I
    - SRR29848600/A1I
    - SRR29848602/H2I
    - SRR29848603/H1I
    - SRR29848605/U2I
    - SRR29848606/U1I

# reference directory for alignment
reference_dir: "./snakemake/src/data/reference"
# define input and output directory
input_dir: "./snakemake/src"
data_input_dir: "./snakemake/src/data"
output_dir: "./snakemake/out/data"

# user email for any API/entrez calls
email: "emailuser@email.com"